version: '3'
 
services:
  web:
    build: 
      context: ./ 
      dockerfile: Dockerfile
    image: ent_infoConnect:v1
    container_name: ent_infoConnect
    ports:
      - "8001:8000"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - postgres_data:/app  
    networks:
      - mynetwork
    env_file:
      - .env
    # Utilisez le nom du réseau personnalisé ici

  db:
    image: postgres:latest
    container_name: bd_infoConnect
    environment:
      POSTGRES_DB: bd_infoConnect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - reseau
     # Utilisez le nom du réseau personnalisé ici
  
  nginx:
    image: 'nginx:1.24-alpine'
    container_name: sitenginxP
    volumes:
      - ./ent_infoConnect:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    ports:
      - '8002:80'
    networks:
      - reseau


volumes:
  postgres_data:
  

networks:
  reseau:
    external: false  

