# Generated by Django 4.2.6 on 2023-11-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agenda",
            fields=[
                ("id_ag", models.AutoField(primary_key=True, serialize=False)),
                ("titre", models.CharField(blank=True, max_length=255, null=True)),
                ("date_deb_ag", models.DateField(blank=True, null=True)),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={"db_table": "agenda", "managed": False,},
        ),
        migrations.CreateModel(
            name="Annonce",
            fields=[
                ("id_ann", models.AutoField(primary_key=True, serialize=False)),
                ("texte", models.TextField(blank=True, null=True)),
                ("date_pub", models.DateField(blank=True, null=True)),
                ("categorie", models.CharField(blank=True, max_length=255, null=True)),
                ("titre", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={"db_table": "annonce", "managed": False,},
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id_doc", models.AutoField(primary_key=True, serialize=False)),
                ("titre", models.CharField(blank=True, max_length=255, null=True)),
                ("date_doc", models.DateField(blank=True, null=True)),
                ("type_doc", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={"db_table": "document", "managed": False,},
        ),
        migrations.CreateModel(
            name="Enseignant",
            fields=[
                (
                    "matricule_en",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(blank=True, max_length=255, null=True)),
                ("prenom", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("sexe", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "mot_de_passe_ensei",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={"db_table": "enseignant", "managed": False,},
        ),
        migrations.CreateModel(
            name="Etudiant",
            fields=[
                (
                    "matricule",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(blank=True, max_length=255, null=True)),
                ("prenom", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.CharField(max_length=255, unique=True)),
                (
                    "mot_de_passe",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("sexe", models.CharField(blank=True, max_length=1, null=True)),
                ("filiere", models.CharField(blank=True, max_length=255, null=True)),
                ("niveau", models.CharField(blank=True, max_length=2, null=True)),
                ("statut", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={"db_table": "etudiant", "managed": False,},
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                ("id_note", models.AutoField(primary_key=True, serialize=False)),
                ("examen", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "valeur",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("date_deb", models.DateField(blank=True, null=True)),
            ],
            options={"db_table": "note", "managed": False,},
        ),
        migrations.CreateModel(
            name="ProfilEns",
            fields=[("id_pr_en", models.AutoField(primary_key=True, serialize=False)),],
            options={"db_table": "profil_ens", "managed": False,},
        ),
        migrations.CreateModel(
            name="ProfilEtu",
            fields=[
                ("id_prof", models.AutoField(primary_key=True, serialize=False)),
                (
                    "mgp",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
            ],
            options={"db_table": "profil_etu", "managed": False,},
        ),
        migrations.CreateModel(
            name="Ue",
            fields=[
                (
                    "code_ue",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(blank=True, max_length=255, null=True)),
                ("credit", models.IntegerField(blank=True, null=True)),
            ],
            options={"db_table": "ue", "managed": False,},
        ),
    ]
