# Generated by Django 4.2.6 on 2023-11-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ent_infoConnect", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResetLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("ETUDIANT", "Etudiant"),
                            ("ENSEIGNANT", "Enseignant"),
                        ],
                        max_length=10,
                    ),
                ),
                ("token", models.CharField(max_length=100)),
                ("expiration_time", models.DateTimeField()),
            ],
        ),
    ]
