# Generated by Django 4.2.6 on 2023-11-13 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ent_infoConnect", "0002_resetlink"),
    ]

    operations = [
        migrations.AlterModelOptions(name="etudiant", options={"managed": True},),
    ]
