# Generated by Django 4.2.6 on 2023-11-13 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ent_infoConnect", "0004_etudiant_last_login"),
    ]

    operations = [
        migrations.AlterModelOptions(name="enseignant", options={"managed": True},),
    ]
