# Generated by Django 4.2.6 on 2023-11-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ent_infoConnect", "0005_alter_enseignant_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="enseignant",
            name="last_login",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
