# Generated by Django 4.2.6 on 2023-11-13 04:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("ent_infoConnect", "0006_enseignant_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="etudiant",
            name="password",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=128,
                verbose_name="password",
            ),
            preserve_default=False,
        ),
    ]
