# Generated by Django 4.2.6 on 2023-11-13 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ent_infoConnect",
            "0008_remove_resetlink_user_type_enseignant_password_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="enseignant", name="password",),
        migrations.RemoveField(model_name="etudiant", name="password",),
    ]
