# Generated by Django 4.2.6 on 2023-11-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ent_infoConnect", "0009_remove_enseignant_password_remove_etudiant_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="enseignant",
            name="password",
            field=models.CharField(default=1, max_length=128, verbose_name="password"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="etudiant",
            name="password",
            field=models.CharField(default=1, max_length=128, verbose_name="password"),
            preserve_default=False,
        ),
    ]
