# Generated by Django 4.2.6 on 2023-11-13 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ent_infoConnect", "0011_resetlink_user_type_alter_resetlink_object_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="enseignant", name="password",),
        migrations.RemoveField(model_name="etudiant", name="password",),
    ]
