# Generated by Django 4.2.6 on 2023-12-07 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ent_infoConnect', '0012_remove_enseignant_password_remove_etudiant_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ue',
            options={'managed': True},
        ),
    ]
