# Generated by Django 4.2.6 on 2023-12-07 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ent_infoConnect', '0013_alter_ue_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='annonce',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='profilens',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='profiletu',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='ue',
            name='matricule_en',
            field=models.ForeignKey(blank=True, db_column='matricule_en', null=True, on_delete=django.db.models.deletion.CASCADE, to='ent_infoConnect.enseignant'),
        ),
        migrations.AddField(
            model_name='ue',
            name='type_ue',
            field=models.CharField(choices=[('F', 'Fondamentale'), ('O', 'Optionnelle')], default='O', max_length=1),
        ),
    ]
