# Generated by Django 4.2.6 on 2023-12-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ent_infoConnect", "0016_document_file"),
    ]

    operations = [
        migrations.RemoveField(model_name="document", name="matricule",),
    ]
