# Generated by Django 4.2.6 on 2023-12-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ent_infoConnect", "0018_alter_document_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
