# Generated by Django 4.2.6 on 2023-12-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent_infoConnect', '0020_rename_type_doc_document_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='date_pub',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
