# Generated by Django 4.2.6 on 2024-01-08 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ent_infoConnect", "0020_rename_type_doc_document_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Requete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("traiter", "Traiter"),
                            ("non_traiter", "Non Traiter"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "code_ue",
                    models.ForeignKey(
                        blank=True,
                        db_column="code_ue",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ent_infoConnect.ue",
                    ),
                ),
                (
                    "matricule_en",
                    models.ForeignKey(
                        blank=True,
                        db_column="matricule_en",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ent_infoConnect.enseignant",
                    ),
                ),
            ],
            options={"db_table": "Requete", "managed": True,},
        ),
    ]
