# Generated by Django 4.2.6 on 2024-01-08 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ent_infoConnect", "0021_requete"),
    ]

    operations = [
        migrations.AlterModelTable(name="requete", table="requete",),
    ]
